### ISSUE TITLE
Bad first impression of the online demo

### ISSUE THREAD

**Issue by piegamesde** [oknozor/unveil-rs#30]
I just found this project, was interested and found the online demo.

- The text in the demo is *way* too large, clipping up to a third of the content. I have some larger text, but still, I have to zoom out to 50% to see the full content
- The transitions regularly get stuck between two slides, or don't really react to keyboard presses.

**Comment by oknozor** [comment]
I currently don't have time to fix the CSS or work on this project at all.  

That being said you are welcome to contribute if you want to help, I will take time to review PRs if needed.
