### ISSUE TITLE
slide animation 

### ISSUE THREAD

**Issue by oknozor** [oknozor/unveil-rs#4]
Reveal js has some css classes for slide transitions, see [#slide-transitions](https://github.com/hakimel/reveal.js/#slide-transitions) and [here](https://github.com/hakimel/reveal.js/search?q=data-transition&unscoped_q=data-transition). 

It would be nice to have something similar in unveil. Ideally it would look like this on a slide :
```markdown 
+++
transition-left: zoom-in fade-out;
trasition-right: default; 
+++
# Title
some dummy content 
```

Note : Currently I am not planning to implement vertical slide navigation (reveal have this). I my opinion it would make slide editing more complicated than it needs to be.

**Comment by lunchboxav** [comment]
Hey, I might be able to give you a hand on this. Mind if I take a look?

**Comment by oknozor** [comment]
You hare very welcome ! Tell me if you need anything.

**Comment by lunchboxav** [comment]
@oknozor I've implemented the JS and CSS for the transition to happen. However, I need to clarify. In your design, the transition mode will be defined in stylematter, right? So, are you expecting that this value passing should be happening from the rust code who builds the html? Or do you have any other suggestion to implement this?

**Comment by oknozor** [comment]
@lunchboxav Firt thank you so much for taking time to do this! 
I think default behavior should be the standard `el.scrollIntoView({behavior: "smooth"});`,
the `transition-left` and `transition-right` css property shall be optional and unset by default, the html classes shall be added at build time if the transition is set in the stylematter.  Please submit a PR so we can test this.

**Comment by lunchboxav** [comment]
Do you mind if I submit PR with the animation implementation first? I haven't been able to implement setting the transition via the stylematter.

**Comment by oknozor** [comment]
No problem, we can figure this out together.
